config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # dashboard
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account  


  resources :posts, only: [:new, :create, :show, :destroy, :update, :edit]
  resources :comments, only: [:create, :destroy]
  root to: "public#homepage"

end

app/models/post.rb
class Post < ApplicationRecord
     
    default_scope { order created_at: :desc }
    mount_uploader :image, ImageUploader
    belongs_to :account
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy

    before_create :set_active
    scope :active, -> {where active: true}
    
    # def total_likes
    #    0 
    # end

    def destroy
        self.delete
    end

    private
    def set_active
        self.active = true
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_post, only: [:show]
    before_action :find_post, only: [:edit, :update, :destroy]
    def new
        @post = Post.new
    end
    

    def create
        @post = Post.new(post_params)
        @post.account_id = current_account.id if account_signed_in?
        
        if @post.save
            redirect_to dashboard_path, flash: { success: "Post created successfully" }
        else
            redirect_to new_post_path, flash: { error: "Post not created" }
        end
    end

    def show
        # @post = Post.find(params[:id])
        @comment = Comment.new
    end

    def update
        # @post = Post.find(params[:id])
        @post.update(post_params)
        redirect_to post_path(@post)
    end

    def edit
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
    
        redirect_to dashboard_path
    end

    private

    def set_post
        @post = Post.find(params[:id]) if params[:id].present?
    end

    def find_post
        @post = Post.find_by id: params[:id]
        return if @post
        flash[:danger] = "Post does not exist"
        redirect_to dashboard_path
    end

    def post_params
        params.require(:post).permit(:description, :image, :image_cache)
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
  
    def post_liked_by_user? post_id
        Like.where(post_id: post_id, account_id: current_account.id).any?
    end
end

app/views/posts/_comments.html.erb
<% post.comments.each do |comment|%>
    <%= link_to profile_picture(comment.account, 25), profile_path(comment.account.username)%>
    <strong><%= link_to comment.account.username, profile_path(comment.account.username)%></strong>
    <% if current_account == comment.account || current_account.admin?%>
        <%= form_tag(comment_path(comment), method: :delete) do %>
        <%= submit_tag "Delete Comment" %>
        <% end %>
    <%end%>
    <%= comment.comment%><br/>
    <p class = "text-muted" > <%= time_ago_in_words comment.created_at%> ago </p>
<%end%>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>

    <%=f.label :image  %>
    <%=f.file_field :image, class: "form-control" %>
    <%=f.hidden_field :image_cache %>


    <%=f.label :description  %>
    <%=f.text_area :description, class: "form-control" %>

    <%= f.submit "Save Post", class: "btn btn-success" %>

<% end %>

app/views/posts/edit.html.erb
<h2> Edit Post: </h2>

<%= render 'form' %>

app/views/posts/like.js.erb
<% if @success == true%>
$(".like-<%= @post.id %>").addClass("active");
<% else  %>
$(".like-<%= @post.id %>").removeClass("active");
<%end%>
$("#post-<%= @post.id %>-likes").text("<%= @post_likes %> likes");

app/views/posts/new.html.erb
<h2> New Post: </h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class = "container">
    <div class="row">
        <div class="col-8">
                <div class = "insta-post">    
                    <div class="post-meta">
                        <% if @post.account.image.thumb.url%>
                            <%= link_to image_tag( @post.account.image.thumb.url, class: "img-circle"), profile_path( @post.account.username) %>
                        <% end %>
                        <%= link_to  @post.account.username,  profile_path( @post.account.username), class: "text-black"%>
                    </div>
                </div>
            <%= image_tag  @post.image.url, class: "img img-fluid" %>
             

            <div class="post-details">
                <div class="post-actions">
                    <span class="btn btn-success like-<%=  @post.id %> <% 'active' if post_liked_by_user?( @post.id)  %> post-like" data-id="<%  @post.id %>">Like</span>
                    <%= link_to post_path( @post.id) do%>
                        <span class="btn btn-success post-comment">Comment</span>
                    <% end %>
                    <% if current_account == @post.account or current_account.admin? %>
                        <%= form_tag(post_path(@post), method: :delete) do %>
                            <%= submit_tag "Delete Post" %>
                        <% end %>
                        <%= button_to 'Edit Post', edit_post_path(@post), method: :get %>
                    <% end %>


                </div>

                <p><strong id="post-<%  @post.id%>-likes"><%=  @post.total_likes_count %> Likes </strong></p>
                <p><strong id="post-<%  @post.id%>-comments"><%= link_to  @post.account.username,  profile_path( @post.account.username), class: "text-black" %> </strong></p>
                
                <%= simple_format  @post.description%>

                <p class="text-muted"> <%= time_ago_in_words  @post.created_at%> ago</p>

                <%= render "posts/comments", post:  @post%>
            </div>
            <div class="comment-box">
                <%= form_for @comment do |f|%>
                    <%= f.hidden_field :post_id, value:  @post.id %>
                    <%= f.hidden_field :return_to, value: "post"%>
                    <div class="input-group">
                        <%= f.text_field :comment, placeholder: "Add comment here...", class: "form-control post-comment"%>
                        <div class="input-group-append">
                            <%= f.submit "Comment", class: "btn btn-success float-right" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="col-4">
        </div>
    </div>
</div>