config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # dashboard
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account  


  resources :posts, only: [:new, :create, :show, :destroy, :update, :edit]
  resources :comments, only: [:create, :destroy]
  root to: "public#homepage"

end

app/views/layouts/_account_nav.html.erb
<li class="nav-item active">
    <%= link_to "Dashboard", dashboard_path, class: "nav-link"%><br/>
</li>

<li class="nav-item">
    <%= link_to "New Post", new_post_path, class: "nav-link"%><br/>
</li>

<li class="nav-item">
    <%= link_to "My Profile", profile_path(current_account.username), class: "nav-link"%> <br/>
</li>

<li class="nav-item">
    <%= link_to 'Sign Out', destroy_account_session_path, method: :delete, class: "nav-link" %> <br/>

</li>

app/views/layouts/_public_nav.html.erb
<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
    <li class="nav-item"><a class="nav-link active" aria-current="page" href="/">Home</a></li>
    <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>InstagramClone</title>

        <link href="css/styles.css" rel="stylesheet" />

   
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
  <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Instagram Clone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <% if account_signed_in?%>
                        <%= render 'layouts/account_nav' %>
                    <% else %>
                        <%= render 'layouts/public_nav' %>
                    <%end%>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="mt-5">
              <%= yield %>               
            </div>
        </div>

  </body>
</html>