config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # dashboard
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" => "accounts#follow_account", as: :follow_account  


  resources :posts, only: [:new, :create, :show, :destroy, :update, :edit]
  resources :comments, only: [:create, :destroy]
  root to: "public#homepage"

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  enum role: [:admin, :member]

  # Set the default role for an account to 'member'
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :member
  end
  
  def full_name
    "#{first_name} #{last_name}"
  end


  def total_followers
    # self.followers.count
    Follower.where(follower_id: self.id).count
  end

  def total_following
    # self.following.count
    Follower.where(following_id: self.id).count
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :authenticate_account!
    before_action :set_account, only: [:profile, :edit, :update, :destroy]
    
    def index
        # user feed

        followers_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
        followers_ids << current_account.id
        following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)

        if current_account.admin?
            @posts = Post.active.order(created_at: :desc)
        else
            @posts = Post.where(account_id: followers_ids).active.order(created_at: :desc)
        end
        @comment = Comment.new

        following_ids << current_account.id
        @follower_suggestions = Account.where.not(id: following_ids).limit(5)


        
    end

    def profile
        # user profile
        @posts = @account.posts.active
    end

    def follow_account
        follower_id = params[:follow_id]
        if Follower.create!(follower_id: current_account.id, following_id: follower_id)
            flash[:success] = "You are now following this account"
        else
            flash[:danger] = "Unable to follow this account"
        end

        redirect_to dashboard_path

    end

    private

    def set_account
        @account = Account.find_by_username(params[:username])
    end
    
end

app/helpers/accounts_helper.rb
module AccountsHelper

    def profile_picture account, width = 100
        image_path = account.image.present? ? account.image.url : "placeholder-profile.jpg"
        image_tag (image_path), width: width, class: "img-fluid rounded-circle"
    end

    def can_edit_profile? profile_id
        account_signed_in? && current_account.id == profile_id
    end
end   

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account|%>
    <div class="recommended-follower">
        <div class = "row">
            <div class = "col-2">
                <%= link_to profile_picture(account, 50), profile_path(account.username) %>
            </div>
            <div class = "col-10">
                <%= form_tag follow_account_path, method: :post, class: "float-right" do %>
                    <%= hidden_field_tag :follow_id, account.id%>
                    <%= submit_tag "Follow", class: "btn btn-primary btn-sm float-right" %>
                <%end%>
                <%= link_to account.username,  profile_path(account.username), class: "text-black"%>
                <p class = "text-muted"><%= account.created_at > 7.days.ago ? "New to Instagram": "Followed by X users"%></p>
            </div>
        </div>
    </div>
<%end%>

app/views/accounts/index.html.erb
<div class = "container">
    <div class="row">
        <div class="col-8">
            <% @posts.each do |post| %> 
                <div class = "insta-post">    
                    <div class="post-meta">
                        <% if post.account.image.thumb.url%>
                            <%= link_to image_tag(post.account.image.thumb.url, class: "img-circle"), profile_path(post.account.username) %>
                        <%end%>
                        <%= link_to post.account.username,  profile_path(post.account.username), class: "text-black"%>
                    </div>
                </div>
            <%= image_tag post.image.url, class: "img img-fluid" %>
             

            <div class="post-details">
                <div class="post-actions">
                    <span class="btn btn-success like-<%= post.id %> <% 'active' if post_liked_by_user?(post.id)  %> post-like" data-id="<% post.id %>">Like</span>
                    <%= link_to post_path(post.id) do%>
                        <span class="btn btn-success post-comment">Comment</span>
                    <% end %>
                    <% if current_account == post.account or current_account.admin? %>
                        <%= form_tag(post_path(post), method: :delete) do %>
                            <%= submit_tag "Delete Post" %>
                        <% end %>
                        <%= button_to 'Edit Post', edit_post_path(post), method: :get %>
                    <% end %>
                </div>

                <p><strong id="post-<% post.id%>-likes"><%= post.total_likes_count %> Likes </strong></p>
                
                <p><strong id="post-<% post.id%>-comments"><%= link_to post.account.username,  profile_path(post.account.username), class: "text-black" %> </strong></p>
                
                <%= simple_format post.description%>

                <p class="text-muted"> <%= time_ago_in_words post.created_at%> ago</p>

                <%= render "posts/comments", post: post%>
            </div>
            <div class="comment-box">
                <%= form_for @comment do |f|%>
                    <%= f.hidden_field :post_id, value: post.id %>
                    <div class="input-group">
                        <%= f.text_field :comment, placeholder: "Add comment here...", class: "form-control post-comment"%>
                        <div class="input-group-append">
                            <%= f.submit "Comment", class: "btn btn-success float-right" %>
                        </div>
                    </div>
                <% end %>
            </div>
            <% end %>
        </div>
        <div class="col-4">
            <div class="account-summary">
                <p>
                    <%= link_to image_tag(current_account.image.thumb.url, class: "img-circle"), profile_path(current_account.username) if current_account.image.present? %>
                    <strong><%= current_account.username %> </strong> <br />
                </p>
                <p><%= current_account.full_name %></p>
            </div>
            <div class = "follower-suggestions">
                <p class = "text-muted"> <strong> People You May Know  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</strong>
                <%= link_to "View All", "#", class: "text-black" %> </p>
                <%= render "accounts/follower_suggestions" %>
            </div>
        </div>
    </div>
</div>

app/views/accounts/profile.html.erb
<div class="container">
    <div class="row">
        <div class="col-4">
            <%= profile_picture @account, 200%>
        </div>
        <div class="col-8 text-left">
            <h1><%= @account.full_name%> </h1>
            <%= link_to "Edit Profile", edit_account_registration_path, class: "btn btn-secondary" if can_edit_profile?(@account.id) || current_account.admin?%>   
            
            <div class="row">
                <div class="col-4">
                    <%= @account.posts.count%> Posts
                </div>      
                <div class="col-4">
                    <%= @account.total_followers%> Followers
                </div>      
                <div class="col-4">
                    <%= @account.total_following%> Following
                </div>    
            </div>
            
            <%# <p> <%= @account.full_name %> <%#</p> %>
            <p> <%= @account.description %> </p>  
            <p> <%= link_to @account.website if @account.website.present?%></p>  
        </div>
    </div>
    <div class="row profile-posts">
        <% @account.posts.each do |post| %> 
        <div class="col-4">
            <div class="insta-post">
                <%= link_to image_tag(post.image.url, class: "img img-fluid"), post_path(post) %>  
            </div>
        </div>
        <% end %>
    </div>
</div>